name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: setup-maven-settings
      uses: s4u/maven-settings-action@v1
      with:
        servers: '[{"id": "github", "username": "x-access-token", "password": "${GITHUB_TOKEN}"}]'

    - name: Build and Deploy to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -Dmaven.wagon.http.pool=false -Dmaven.test.skip=true clean deploy
      
    - name: Retrieving artifact name
      id: getfilename
      run: echo "::set-output name=file::$(cd target && ls pma-*.jar)"
    - name: Storing artifact on GitHub Actions
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.getfilename.outputs.file }}
        path: target
        

